### PR TITLE
Add node18 `18.0.0`

### PR DESCRIPTION
**Pull request by omBratteng**
Unsure wether to add it now, or when Active LTS starts in October.

### CODE REVIEW

**Comment by loosebazooka** [comment]
I would wait for active LTS please.

**Comment by omBratteng** [comment]
I just opened this now, as according to the [`SUPPORT_POLICY.md`](https://github.com/GoogleContainerTools/distroless/blob/main/SUPPORT_POLICY.md#node) it says even numbered releases that are current, active or LTS maintenance.
Which by my interpretation, v18 is now current release, then in October it enters Active LTS, and 2023-10-18 it enters Maintenance LTS.

I'm fine with either. But perhaps the [`SUPPORT_POLICY.md`](https://github.com/GoogleContainerTools/distroless/blob/main/SUPPORT_POLICY.md#node) could be changed to say only Active LTS or Maintenance LTS?

> Production applications should only use Active LTS or Maintenance LTS releases.
> _https://nodejs.org/en/about/releases/_

**Comment by loosebazooka** [comment]
lol no you're right, I wrote that policy, I think I misunderstood what was going on here... whoops. Lets add it in.

**Comment by omBratteng** [comment]
> Lets add it in.

node18 or the bit in the [`SUPPORT_POLICY.md`](https://github.com/GoogleContainerTools/distroless/blob/main/SUPPORT_POLICY.md#node)?

v18 was just released, so I haven't gotten to test it yet, so I'll do testing locally tomorrow, that uses `nodejs:18` image.

Also need to wait till [`node:18`](https://hub.docker.com/_/node) has been released too

**Comment by loosebazooka** [comment]
Oh sorry, lets add the node18 image. It would be nice to standardize the naming like the other images though.

for example `node:16` -> `node16:latest`

**Comment by omBratteng** [comment]
You mean renaming `gcr.io/distroless/nodejs:16` to `gcr.io/distroless/node:16`. And adding an alias `gcr.io/distroless/node16:latest`?
Could be done in another PR

**Comment by loosebazooka** [comment]
yeah, makes sense I was thinking about it for java and brought it up here... no need to actually handle it here.

**Comment by omBratteng** [comment]
Seems to work fine, and `node:18` images have finally been published, so this PR is ready for review

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
