### PR TITLE
Publish non-root Java images

### PR DESCRIPTION
**Pull request by pierDipi**
Images haven't been published since the cloudbuild file doesn't reference them in the images section.

Fixes https://github.com/GoogleContainerTools/distroless/issues/615
Context https://github.com/GoogleContainerTools/distroless/pull/617

cc @chanseokoh

### CODE REVIEW

**Comment by chanseokoh** [comment]
Ah, that's what we've missed. However, there's another problem. GCB failed to run, as a step arg became too long.

> Your build failed to run: generic::invalid_argument: invalid build: invalid .steps field: build step 2 arg 1 too long (max: 4000)

Cloud you also break down the step? Like this recent #619.

**Comment by pierDipi** [comment]
Sure!

**Review by chanseokoh — APPROVED** [review]
Thanks. The images should be published within an hour (typically much earlier than that) if nothing goes wrong again.

**Comment by chanseokoh** [comment]
All good now. The images should have been published.

**Pull request merged**
