### PR TITLE
Fix: distroless/java:11 missing liblcms2.so.2 #329

### PR DESCRIPTION
**Pull request by mgubaidullin**

### CODE REVIEW

**Comment by chanseokoh** [comment]
Thank you! Could follow the instructions to sign the CLA and leave a comment to make the bot happy?

**Comment by mgubaidullin** [comment]
I'm added to the group of authorized contributors

**Comment by mgubaidullin** [comment]
I don't have write access to this repository to merge pull request.

**Comment by chanseokoh** [comment]
I see. I'll merge it. Thanks again for your contribution. The images will be auto-published soon.

**Pull request merged**
