### PR TITLE
experimental/python3: Add Debian 11 support

### PR DESCRIPTION
**Pull request by evanj**
This builds on my //cc change, which has not yet been merged (#795).
This edits the tests a bit to ensure the container works. I have
not tested this, beyond getting the tests to pass. However, those
tests do check that all the standard library modules work, so
this is at least a good starting point.

My plan is to rebase this when #795 is merged, and then turn this into a "real" pull request.

### CODE REVIEW

**Comment by evanj** [comment]
Given some fast merging of the cc change, this is now ready for review!

**Comment by dlorenc** [comment]
This one may or may not work because of the recent build changes to use the GCS cache in #783. I'll wait for @loosebazooka to take a look next week, there might be another list we have to sync these new packages into.

**Comment by loosebazooka** [comment]
The cache isn't being used yet. I don't know how much more load we can put on debian snapshots yet though, I would prefer to finish the cache based build before we do more.

**Comment by loosebazooka** [comment]
hey @evanj sorry we didn't get to this before making a bunch of changes? Would you be okay cleaning up the PR?

**Comment by evanj** [comment]
I am happy to! It may take me a week or two to get around to it though.

**Comment by loosebazooka** [comment]
Yeah no problem, I think in the meantime I'm going to see if I can generate the arm64 ld.so.cache thing somewhere (or use qemu)

**Comment by evanj** [comment]
I got to this a bit sooner than expected! I rebased my change on top of the latest main. It passes the tests for me.

**Comment by loosebazooka** [comment]
lgtm, I just want to check the dependencies real quick.

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
