### PR TITLE
Update Bazel 4.2.1 -> 5.1.1 (LTS release)

### PR DESCRIPTION
**Pull request by omBratteng**
Bazel 4.2.1 is broken on macOS >= 12.3, as python 2 is no longer supported. And you're unable to symlink `python3` to `python` in `/usr/bin`.

## Related issues:
- https://github.com/google/mediapipe/issues/3184

## Related commit:
- https://github.com/bazelbuild/bazel/commit/2945ef5072f659878dfd88b421c7b80aa4fb6c80

### CODE REVIEW

**Comment by loosebazooka** [comment]
This is nice, we might be able to restructure the codebase around bazel mod, making it easier for people to extend distroless for their own use.

**Comment by loosebazooka** [comment]
hah, I was just thinking out loud :smile:, waiting for CI to finish and then I'll merge this and see how the release goes.

**Comment by omBratteng** [comment]
Looks like CI finished without issues.

**Review by loosebazooka — APPROVED** [review]

**Comment by omBratteng** [comment]
@loosebazooka did this break Google Cloud Build / publish-images workflow?
https://github.com/GoogleContainerTools/distroless/runs/6192816785

**Comment by loosebazooka** [comment]
Yeah I think we got the cloud builder sha wrong?

**Comment by loosebazooka** [comment]
That's pretty weird -- the image does exist, maybe the workflow just being flaky.

**Pull request merged**
