### PR TITLE
Switch to docker builder

### PR DESCRIPTION
**Pull request by mattmoor**
Talking to @ImJasonH this is the recommendation from the GCB team, see:
https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker#docker

### CODE REVIEW

**Comment by mattmoor** [comment]
I am verifying this with `gcloud builds submit --substitutions=COMMIT_SHA=deadbeef` now, but it's already passed the first `docker tag` stanza 🤞

**Comment by chanseokoh** [comment]
Would you update `java/cloudbuild.yaml` too?

**Comment by mattmoor** [comment]
Sure, didn't realize there were two

**Comment by mattmoor** [comment]
done

**Comment by mattmoor** [comment]
alright the cloud build run of the first is done, lmk if you want me to do the java one too for good measure.

**Review by chanseokoh — APPROVED** [review]
We'll see about the Java build. I'll update if something goes wrong.

**Pull request merged**
