### PR TITLE
Add a buildifier github action

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Comment by mattmoor** [comment]
I added some errors in a prior commit and you can annotations like this on the PR code:
image

**Comment by chanseokoh** [comment]
Basically this seems like a nice idea, but because we are already running buildifier on Travis, I am not sure why we want to add another duplicate check? Is this really necessary? Given the current state of Distroless, I'm trying to not increase code complexity and maintenance burden as much as possible.

**Comment by mattmoor** [comment]
@chanseokoh I am trying to eliminate the travis check, because we don't need this check running on multiple architectures.

**Comment by chanseokoh** [comment]
Sounds good. Just make sure to keep it in `./test.sh` or document running buildifier locally so that it makes contributors run it before putting up a PR that has a style issue.

**Comment by mattmoor** [comment]
I removed the old way and documented both this and `pylint` in CONTRIBUTING.md

**Comment by mattmoor** [comment]
I'm going to look at pylint next.

**Review by chanseokoh — APPROVED** [review]

**Pull request merged**
