### PR TITLE
Make example node.js Dockerfile more declarative

### PR DESCRIPTION
**Pull request by luke-perry**
Include dependency install in node.js example Dockerfile to make need of multistage build more clear.

### CODE REVIEW

**Comment by luke-perry** [comment]
@googlebot I signed it!

**Comment by chanseokoh** [comment]
Thanks @luke-perry! I don't know Nodejs, but someone told me this should have been included. He also told me the recommendation is to use `npm ci` now. Can you update the PR to use `npm ci`?

**Comment by luke-perry** [comment]
@chanseokoh Thanks for the feedback! :) Yeah, I emotionally battled over if it would be more clear to use the more CI/CD appropriate `npm ci --only=production` or `npm install`. lol I'll make the update.

**Comment by luke-perry** [comment]
@chanseokoh Update complete for`npm ci` command. Thanks!

**Pull request merged**
