### PR TITLE
WORKSPACE: Add buster-updates to debian10 to update ca-certificates

### PR DESCRIPTION
**Pull request by evanj**
This updates ca-certificates to 20200601~deb10u1, which was added to
buster-updates. This may cause problems when packages are added to
buster-updates, but then updated again into the stable point releases.
For example, tzdata version 2019c-0+deb10u1 was added to
buster-updates, then later tzdata version 2020a-0+deb10u1 was added
to buster for the 10.4 "point release". Since dpkg_list takes the first
package it finds, it finds the older tzdata version.

We should eventually fix the dpkg_list function to actually attempt to
order by version numbers to resolve this. For now, I've manually pinned
the tzdata version to ensure it gets the latest version.

### CODE REVIEW

**Comment by evanj** [comment]
Hmm... I see that TravisCI is not running on these pull requests. It does appear to be running on Master though.

**Comment by chanseokoh** [comment]
Hmm... I'm not sure what Travis is not firing. Happening on other PRs too. I suspect a temporary outage.

**Comment by chanseokoh** [comment]
I suspect it's a temporary outage that Travis results are not reported. Happening on all PRs. In any case, I think #526 upgraded Java.

```
env var JAVA_VERSION value 8u252 does not match expected value: 8u242
```

Could you fix the test?
```
$ git grep 8u242
java/testdata/java8.yaml:      value: '8u242'
java/testdata/java8_debug.yaml:      value: '8u242'
```

**Comment by chanseokoh** [comment]
Could you merge with master to run fixed tests on this PR?

**Pull request merged**
