### PR TITLE
fix link to python2.7 hello word example

### PR DESCRIPTION
**Pull request by karousn**

### CODE REVIEW

**Comment by lathama** [comment]
@karousn can you sign the CLA or is there an issue? If you can't sign it please close this PR.

**Comment by karousn** [comment]
@lathama will done

**Comment by karousn** [comment]
@lathama will done.

**Comment by dlorenc** [comment]
I've manually verified that @karousn has signed the CLA. This should be good to merge, not sure why the bot isn't picking it up.

**Pull request merged**
