### PR TITLE
feat: Initial support of Debian 12 (bookworm, testing) for base and cc

### PR DESCRIPTION
**Pull request by siketyan**
This pull request adds an initial support of the latest Debian version 12 (codename "bookworm") for base and cc images.

On this version, libssl1.1 is no longer available and superseded by libssl3. So that I added distro-specific deb dependencies to base/base.bzl.

### CODE REVIEW

**Comment by loosebazooka** [comment]
Debian 12 has no release date yet. Once it is released, we'll add in support for this. I believe it is sometime in 2023?

**Comment by theoludwig** [comment]
> We've made major changes to the build. So closing this. Debian 12 (by estimate) wont be out till late in the year.

Debian v12 has been released! @loosebazooka :smile:
See: #1337

**Comment by robd003** [comment]
@loosebazooka Can we re-open this pull request and merge it now that Debian 12 is available?

**Comment by loosebazooka** [comment]
I'm on parental leave till the end of July. So it'll be a little slow till
then.

**Comment by robd003** [comment]
Congrats on the new child!

**Pull request closed without merging**
