### PR TITLE
refactor: start using rules_distroless

### PR DESCRIPTION
**Pull request by thesayyn**
@loosebazooka please take your time reviewing and testing this as rules from rules_distroless might not be identical to their counterparts here. I'll push new commits instead of rebasing to make it easier for you to review them.

Changes 

- replace `locale` 
- replace `cacerts`
- replace `java_cacerts`
- remove rules_docker
- replace group passed and home
- create `common` directory to move locale & cacerts & group & passwd into single BUILD file for reuse.

### CODE REVIEW

**Comment by thesayyn** [comment]
Tests mostly should catch any mistakes here but it's good to be extra careful

**Comment by loosebazooka** [comment]
Sorry, we've discussed changed in another channel. I think they'll reflect here eventually. Still working out things.

**Comment by thesayyn** [comment]
This should be ready now @loosebazooka

**Comment by loosebazooka** [comment]
examples/nonroot/ seems to reference rules_docker?

**Comment by loosebazooka** [comment]
@thesayyn this otherwise looks fine. I think there's a minor update required in examples

**Comment by loosebazooka** [comment]
does this need an update from rules distroless to match the perms on the user files?

**Comment by thesayyn** [comment]
Yes, some tests are failing because of that, will get to this soon.

**Comment by loosebazooka** [comment]
you should be able to just run buildifier directly to rectify all issues: https://github.com/GoogleContainerTools/distroless/blob/main/CONTRIBUTING.md#code-style

**Comment by thesayyn** [comment]
@loosebazooka this is ready

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
