### PR TITLE
Add option in cacerts rules to include additional ca certs

### PR DESCRIPTION
**Pull request by dpoll**
This features allow adding additional ca certificates in the cacerts rule. This is useful when ca certs are needed which are not part of the `ca-certificates` Debian package.

### CODE REVIEW

**Comment by chanseokoh** [comment]
The merge conflict should be resolved first before this can be reviewed.

**Comment by christopherhein** [comment]
@dpoll any update on this?

**Comment by OuadiaGamrane** [comment]
any updates please on this ?

**Comment by loosebazooka** [comment]
Hrmm, yeah I can take a look, @dpoll would you like to clean up this PR? @OuadiaGamrane / @christopherhein you're also welcome to create a new PR with the changes against the current main branch.

**Comment by gaby** [comment]
Any updates on this? It's been over 2 years since PR was created...

**Comment by gaby** [comment]
Friendly bump @dpoll @loosebazooka

**Comment by loosebazooka** [comment]
@gaby we always encourage users to create a new pr of this is pressing for them

**Comment by gaby** [comment]
@loosebazooka I don't really understand how to apply the changes from this PR into a new one since the `extract.sh` is nowhere to be found. I'd say to close this since @dpoll is not even active on Github.

**Comment by dpoll** [comment]
Hey, sorry for my super slow response. I just tried to fix the conflict. Not sure if it works correctly since I can't remember how I tested this before. I'll push what I have later today.

**Comment by dpoll** [comment]
I merged in main tried get the feature working with all the changes but I'm having some issue. I pushed the changes but `test.sh` is still not passing for me, I think there is some issue with the way the file paths argument is getting passed in. 

I'm not sure what the fix is here. If someone has some idea how to help me that would be great, or go ahead and make the change yourself.

**Comment by xcheng75** [comment]
is this still needed?

**Comment by gaby** [comment]
@xcheng75 Yes, specially for corporate networks, and airgap networks.

**Comment by loosebazooka** [comment]
So this PR is just extremely out of date at this point. If anyone wants to redo it for the new repo structure, please create a new PR and I will review it.

**Pull request closed without merging**
