### PR TITLE
Update package manager

### PR DESCRIPTION
**Pull request by petermylemans**
Goal: get rid of the python package manager and switch to a more stable solution that uses bazel builtin functions as much as possible.

Updating packages is as easy as running `bazel run update_deb_packages`. This will update the workspace with the latest available versions for the respective distribution and/or sources. I've also added PGP validation for the release files to reject any corrupted files.
Third party sources (e.g.  AdoptOpenJDK deb repo) are possible, but not in use at the moment.

- [X] Archive dependencies should live in the WORKSPACE file, but due to the sheer number of packages, it is getting big... Need another approach?
- [X] packages_amd64_debian10 and packages_arm64_debian10 are very similar in terms of packages. The reason I can't join them into a single rule is that bazel doesn't support nested dicts as attributes as far I know. 
I'm also not sure whether all packages exist in all archs, so might be best to keep them separate
` deb_packages(packages = { "some_pack": { "amd64": "url...", "arm64": "another url" } )` is not allowed.
- [X] Have a look at JAVA_VERSION FIXME
- [X] Have a look at the /etc/os-release FIXME. Should be included in base-files.
- [X] Clean up updater and version files from "old solution"
- [X] Clean up python package manager. Only dpkg_extract.sh remains (due to usage in locale en cacerts rules).

Relates to #602 #153

### CODE REVIEW

**Comment by chanseokoh** [comment]
Cool stuff! Haven't looked into it seriously, but it appears to clean things up a lot as it depends on an external rule. I just hope the rule is well supported in the long run.

> I'm also not sure whether all packages exist in all archs,

This is not the case. I've seen it in https://github.com/GoogleContainerTools/distroless/pull/612#issue-500157699:

> excluded "libunwind8" package for Debian9/10 s390x (s390x repos do not have this package)

**Comment by petermylemans** [comment]
Yes I also saw that PR, so I've opted to use a .bzl file per repo per arch for that reason. 

With respect to maintaining the external rules: I guess that's the story of all OSS projects especially the small one's. 

In this case it is a limited code base, but useful beyond distroless. You could e.g. use it to extend a distroless base image with additional debs in a reproducible way. 

I'm happy to move the code towards an organisation if that alleviates some of your concerns. In this case I look to some of the other rules packagers for guidance?

**Comment by chanseokoh** [comment]
> I'm happy to move the code towards an organisation if that alleviates some of your concerns.

Looks like no one at Google wants to be receive it. Do you know some organization to move the code to?

**Comment by petermylemans** [comment]
Not at the moment apart from creating a new one?

But one could argue that it is probably better in that case to make it internal to distroless? 
I guess the reasoning of other projects is "too specific to distroless' use case"?

**Comment by petermylemans** [comment]
I'll have to rethink the approach a bit based on the fact that packages can disappear from ftp master. 
Snapshots (as we are currently using it) seems to be the only way to have fully reproducible builds.

**Pull request closed without merging**
