### PR TITLE
Publish Java Debian 10 images (Java 11 only)

### PR DESCRIPTION
**Pull request by chanseokoh**
I've already cleaned up the `BUILD` file in #430 that can now publish Java Debian 10 images.

Now I only need to do this on the `cloudbuild.yaml` file, and we should be good.

However, I realized the problem that `cloudbuild.yaml` cannot have more than 100 steps. @donmccasland can we break it up into two files, `cloudbuild1.yaml` and `cloudbuild2.yaml`?

### CODE REVIEW

**Comment by floriankoch** [comment]
@chanseokoh   any chance to get this in?

**Comment by chanseokoh** [comment]
There's one problem with this PR. This modifies `cloudbuild.yaml` and grows the steps beyond 100. `gcloud builds submit` will refuse to run it. Maybe we could break down the YAML file into two, but that would probably require changing some backend release process. I don't have control over the backend. @donmccasland what's best to resolve this issue?

**Comment by stuartgunter** [comment]
Hello. I just wanted to find out if there's a plan to resolve the `cloudbuild.yaml` issues and release the `java-debian10` images in the near future?

**Comment by gertvdijk** [comment]
> Hello. I just wanted to find out if there's a plan to resolve the `cloudbuild.yaml` issues and release the `java-debian10` images in the near future?

I'm hoping this too. It's the last piece that's holding me back to ditch all of Debian 9 in my project.

FWIW, I've been exploring the possibility of just depending on the Bazel target as base, building the image from source myself in my own Bazel project. However, that seems not very doable either (#465).

The only way it works for me right now is to build the image myself from the distroless workspace and publish it myself:

1. Build the image and load it into the Docker daemon (Java 11 is the only Java version on Debian 10):

       bazel run //java:java11_debian10 -- --norun

   This should show output like:

   > Loaded image ID: sha256:[...]
   > Tagging [...] as bazel/java:java11_debian10

1. Tag it with your own tag (`$MYTAG` to be part of a private repository):

       docker tag bazel/java:java11_debian10 $MYTAG

1. Push it:

       docker push $MYTAG

**Comment by chanseokoh** [comment]
I'll think of something to overcome the 100-step limit on GCB.

**Comment by chanseokoh** [comment]
I should have come up with this solution earlier. Much cleaner and improved readability a lot.

I'll submit this PR. The Java 11 on Debian 10 images will automatically go live soon.

**Pull request merged**
