### PR TITLE
Add `nonroot` to nodejs images

### LINKED ISSUE #892: Compliance issue with distroless nodejs image.
Hi team, We found below issue in nodejs distroless image. Is there any other a non-root image for nodejs without this issue which we can use, or have you fixed this known vulnerability highlighted by: CIS_Docker_v1.20 - 4.1? Could you please help with this?

Image details:-  distroless/nodejs:14

image

### PR DESCRIPTION
**Pull request by omBratteng**
I came across #892, and thought I'd give it a go to add `nonroot` images for node

Closes #892

### CODE REVIEW

**Comment by omBratteng** [comment]
So many places to add root/nonroot. I _think_ I got them all 🤞🏻

**Comment by omBratteng** [comment]
Yay, all tests went through 🎉

**Comment by loosebazooka** [comment]
I think it might be time to standardize the naming of nodejs images to be similar to the others.

```
nodejs<version>-debian<version>:{root, non-root, root-debug, non-root-debug}
```

We can leave the old naming as legacy for now and deprecate those in ~6 months ?

**Comment by omBratteng** [comment]
I see no issue with that. I can do that in another PR.

How about deprecate the old naming 2023-04-30, that matches with the EOL of node 14, so we can drop the non-manifested builds too.

**Comment by omBratteng** [comment]
Depends on #1086

**Comment by loosebazooka** [comment]
Does this need a rebase or something?

**Comment by omBratteng** [comment]
I did a rebase, but I think I did something wrong during it.
I'll see what's broken and get the tests fixed.

**Comment by omBratteng** [comment]
There, that should fix it 🤞🏻. I had forgotten to add the root in name of the legacy formats

**Review by loosebazooka — APPROVED** [review]
thanks!

**Comment by omBratteng** [comment]
I did not create nonroot variants for the legacy tags, hoping that's fine?

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
