### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by martin-sweeny**
Remove reference to `gcr.io/distroless/static`

### CODE REVIEW

**Comment by martin-sweeny** [comment]
Man, I'm de-googling myself. Can you even call a project open source if you only accept PRs from your users? I just wanna correct your docs lol

**Comment by loosebazooka** [comment]
I don't make the lawyer rules.

**Comment by loosebazooka** [comment]
Can you explain the reasoning behind these changes? Both `base` and `static` still exist. And there is a distinction between them.

**Comment by dekkagaijin** [comment]
> Can you explain the reasoning behind these changes? Both `base` and `static` still exist. And there is a distinction between them.

+1

`/base` isn't terrible descriptive but it is the dynamically-linked counterpart to `/static`

**Comment by martin-sweeny** [comment]
Oh, you know what, I got confused. https://github.com/GoogleContainerTools/distroless#docker shows 5 different image options, but they don't link to unique readmes. Ignoring the header, I didn't realize it was the same doc for both `base` and `static`. My bad!

**Pull request closed without merging**
