### PR TITLE
Bump `nodejs22` to `22.5.0`

### PR DESCRIPTION
**Pull request by omBratteng**

### CODE REVIEW

**Review by loosebazooka — APPROVED** [review]

**Comment by omBratteng** [comment]
@loosebazooka the report diff keeps failing on PRs made by contributors outside the GoogleContainerTools org. If you update the workflow so that it has write permissions to pull_request, it should no longer fail for external contributors.

**Comment by smorimoto** [comment]
Note that you will have to wait a while to merge this change: https://github.com/nodejs/node/pull/53934

**Comment by omBratteng** [comment]
I guess we probably can skip this version, and wait for a patched version, 22.5.1 probably.

**Comment by loosebazooka** [comment]
> @loosebazooka the report diff keeps failing on PRs made by contributors outside the GoogleContainerTools org. If you update the workflow so that it has write permissions to pull_request, it should no longer fail for external contributors.

Yeah this was more to detect issues on large scale changes we were doing

**Pull request closed without merging**
