### PR TITLE
remove binary build artifact

### PR DESCRIPTION
**Pull request by loosebazooka**
Signed-off-by: Appu Goundan <appu@google.com>

#771 

~~I can't imagine this was intentionally added in.~~ lol it was my bad

### CODE REVIEW

**Comment by loosebazooka** [comment]
this is a little more involved than I thought

**Comment by chanseokoh** [comment]
I'm curious if tar files count as binary artifacts. 
```
$ find . -name '*.tar'
./base/tmp.tar
./base/nsswitch.tar
```

**Comment by loosebazooka** [comment]
I'm not sure, @jeffmendoza? are tars considered binaries?

**Comment by jeffmendoza** [comment]
It's only `examples/cc/bin/hello` here I believe.

**Comment by dlorenc** [comment]
I think they should be considered binary artifacts.

**Comment by jeffmendoza** [comment]
https://github.com/ossf/scorecard/blob/main/checks/binary_artifact.go#L50 fyi

**Comment by jeffmendoza** [comment]
https://github.com/ossf/scorecard/issues/759

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
