### PR TITLE
update cosign to use release v1.3.1

### PR DESCRIPTION
**Pull request by cpanato**
- update cosign to use release v1.3.1

### CODE REVIEW

**Comment by loosebazooka** [comment]
Dan has no power here. He left that behind to find a new life.

**Comment by loosebazooka** [comment]
@priyawadhwa does the tekton config live somewhere in here and it needs to be updated?

**Comment by cpanato** [comment]
then I need your help @loosebazooka :)

**Review by dlorenc — APPROVED** [review]

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
