### PR TITLE
Add Erlang base image

### PR DESCRIPTION
**Pull request by magnetised**

### CODE REVIEW

**Comment by magnetised** [comment]
Sorry - didn't mean to make a PR here 😳

**Comment by Nezteb** [comment]
@magnetised Out of curiosity, is there a reason you didn't want to add Erlang to the official `GoogleContainerTools` repo? I was looking at adding an Erlang/Elixir image but found this first. 😄

**Comment by loosebazooka** [comment]
We don't really intend of supporting the world. The build and maintenance is expensive so we try to keep our support scoped pretty tightly. Although there are offerings from chainguard or ubuntu or other vendors that might satisfy your needs.

**Comment by dlorenc** [comment]
If you're interested we have erlang packaged in wolfi and would add an image for it!
https://github.com/wolfi-dev/os/blob/main/erlang.yaml

The image would go here: https://github.com/chainguard-images/images/tree/main/images

**Comment by Nezteb** [comment]
@loosebazooka Totally understandable; I figured I'd ask. 😄 

@dlorenc Neat! Thanks for the info! 🥳

**Pull request closed without merging**
