### PR TITLE
feat: Add Node.js support for Debian 12

### PR DESCRIPTION
**Pull request by siketyan**
This pull request adds Node.js (v18, v20) language support for Debian 12 (bookworm).
References #1398.

### CODE REVIEW

**Comment by loosebazooka** [comment]
I think @omBratteng is trying to handle this in #1317 ?

**Comment by siketyan** [comment]
Yes, but it looks still in progress. I think we can merge #1317 first and then catch-up for Debian 12 support in this PR.

**Comment by omBratteng** [comment]
You can just add Debian 12 support, and I'll rebase my PR to get those changes. I'm on a work trip now, so I don't have that much time to it right now.

**Review by loosebazooka — COMMENTED** [review]
looks good, just need the debian 12 tests

**Comment by siketyan** [comment]
@loosebazooka 
I think we already have Debian 12 tests, as iterated in nodejs/BUILD.

```
❯ bazel test //nodejs:nodejs18_root_arm64_debian12_test
INFO: Build option --test_env has changed, discarding analysis cache.
INFO: Analyzed target //nodejs:nodejs18_root_arm64_debian12_test (166 packages loaded, 12586 targets configured).
INFO: Found 1 test target...
Target //nodejs:nodejs18_root_arm64_debian12_test up-to-date:
  bazel-bin/nodejs/nodejs18_root_arm64_debian12_test.sh
INFO: Elapsed time: 3.538s, Critical Path: 0.81s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
//nodejs:nodejs18_root_arm64_debian12_test                      (cached) PASSED in 5.2s

Executed 0 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

**Comment by loosebazooka** [comment]
you're right my bad, the testdata files are the same for both debian versions.

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
