### PR TITLE
WORKSPACE: Update to latest Debian snapshots

### PR DESCRIPTION
**Pull request by evanj**
This includes the Debian 10.4 point release. The following Debian 10
packages were updated:

    base-files       10.3+deb10u4
    libgnutls30       3.6.7-4+deb10u4
    libldap-2.4-2     2.4.47+dfsg-3+deb10u2
    libldap-common    2.4.47+dfsg-3+deb10u2
    tzdata            2020a-0+deb10u1

### CODE REVIEW

**Comment by chanseokoh** [comment]
Ah, wait. It seems like our automatic publishing is broken.

**Comment by chanseokoh** [comment]
This is it: https://github.com/GoogleContainerTools/distroless/pull/521#issuecomment-643320096 Will fix this shortly.

**Comment by evanj** [comment]
Hmm... For glibc: 2.28-10 is still the latest version in Debian10 as per your previous comment on that thread.

**Comment by chanseokoh** [comment]
FTR: this [upgraded Java 8 on Debian 9](https://github.com/GoogleContainerTools/distroless/pull/527#issuecomment-643331985) from 8u242 to 8u252 (and broke tests).

**Pull request merged**
