### PR TITLE
Add java 17 support for debian 12

### PR DESCRIPTION
**Pull request by Sineaggi**
Java 11 (jre/jdk) is not available under debian 12.

```
$ apt-get install openjdk-11-jdk-headless
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package openjdk-11-jdk-headless is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  openjdk-17-jre-headless

E: Package 'openjdk-11-jdk-headless' has no installation candidate
```

### CODE REVIEW

**Comment by Sineaggi** [comment]
Referencing https://github.com/GoogleContainerTools/distroless/issues/1398

**Comment by loosebazooka** [comment]
@Sineaggi ready for review?

**Comment by Sineaggi** [comment]
> @Sineaggi ready for review?

I think so, sorry about the churn.

**Comment by Sineaggi** [comment]
Few things to note. There's a bit of copy paste, some necessary and some potentially avoidable with a refactor.

There's a library difference in libpcre2 between debian 11 and 12.

I ran thru the list of packages that openjdk depends on and double-checked what was necessary and what wasn't. I'm wondering if we can move to nossl as the base for java images in the future? Seems like cups (and related dependencies) are the only things ssl would be needed for.

**Comment by loosebazooka** [comment]
yeah we can probably remove libssl from the java image? Much easier to start without it and add it back in later if there's a legitimate reason

**Comment by Sineaggi** [comment]
@loosebazooka would you prefer the nossl here, on in a separate pr?

**Comment by loosebazooka** [comment]
here is good

**Comment by Sineaggi** [comment]
> here is good

Sounds good, done.

**Review by loosebazooka — APPROVED** [review]

**Comment by loosebazooka** [comment]
Thanks so much for doing this!

**Pull request merged**
