### PR TITLE
Publish static images as manifest lists.

### PR DESCRIPTION
**Pull request by mattmoor**
A sample run of this (on my project) produced:
```
    crane manifest gcr.io/mattmoor-knative/static:nonroot
    {
       "schemaVersion": 2,
       "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
       "manifests": [
          {
             "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
             "size": 526,
             "digest": "sha256:2b4a48f7c192111b0ff59633f1ac68f0079b8e8306bf0c5cb55169241ba464c9",
             "platform": {
                "architecture": "amd64",
                "os": "linux"
             }
          },
          {
             "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
             "size": 526,
             "digest": "sha256:9169d04187d456913f000daeddc3fa2c2ae2e27dca5297b697d5c1d6f5b132c7",
             "platform": {
                "architecture": "arm64",
                "os": "linux"
             }
          }
       ]
    }
```

Based on: https://github.com/GoogleContainerTools/distroless/pull/586
Fixes: https://github.com/GoogleContainerTools/distroless/issues/583

### CODE REVIEW

**Comment by mattmoor** [comment]
I see arm64 images under https://gcr.io/distroless/static 🤩

**Comment by mattmoor** [comment]
Ok, I redeployed https://pizzaplanetv1-test-image.default.mattmoor.io changing just `.ko.yaml` to include `:nonroot-arm64` and it works 🤩

**Review by dekkagaijin — APPROVED** [review]
Thanks for dragging distroless kicking and screaming into its archful future

**Comment by morlay** [comment]
Can't wait to use this to add distroless build of istio https://github.com/querycap/istio

**Comment by mattmoor** [comment]
@morlay those should be pretty easy to add next, I'm starting small 😉

**Comment by morlay** [comment]
@mattmoor  Cool. i see the codebase is upgraded. Waiting those images to land on gcr.io

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
